### ISSUE TITLE
'Uncategorized links' exception caught with EE v3.2.0

### ISSUE THREAD

**Issue by tonyynot** [EllisLab/Wiki#2]
When clicking "Uncategorized links", the following exception is thrown:

**No such property: 'logger' on EllisLab\ExpressionEngine\Legacy\Facade**

/opt/sites/utilities/wiki/htdocs/system/ee/EllisLab/ExpressionEngine/Legacy/Facade.php:107

![screen shot 2016-03-15 at 3 05 00 pm](https://cloud.githubusercontent.com/assets/9784303/13790540/5eefb68c-eabf-11e5-8cfd-8b125758d26f.png)

**Comment by robinsowell** [comment]
Thanks for the heads up!  I've pushed up a fix - you can see the diff [here](https://github.com/EllisLab/Wiki/commit/e84f769fe0d35ec07a1e28248dab3c48af671f5d) and patch or simply pull down a fresh copy and update.

Does that get everything working for you?

**Comment by tonyynot** [comment]
@robinsowell that works! Thanks a lot! :+1:

**Comment by robinsowell** [comment]
;)  Thanks for the confirmation.  I'm quite liking having the wiki in github!
